version: '3.3'

volumes:
  foodgram_backend_static:
  foodgram_backend_media:
  postgres_data:

services:

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    volumes:
      - ../frontend/:/app/result_build/

  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  backend:
    image: dudeinn/foodgram_backend:latest
    restart: always
    volumes:
      - foodgram_backend_static_value:/app/static/
      - foodgram_backend_media_value:/app/media/
      - ./import_data/:/app/data/
    depends_on:
      - db
    env_file:
      - ./.env

  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - foodgram_backend_static:/var/html/static
      - foodgram_backend_media:/var/html/media
    depends_on:
      - backend
