version: '3.8'

services:

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    volumes:
      - ../frontend/:/app/result_build/

  db_foodgram:
    image: postgres:13.0-alpine
    container_name: foodgram_db
    volumes:
      - foodgram_data_volume:/var/lib/postgresql/data/
    env_file:
      - .env

  foodgram_backend:
    image: dudeinn/foodgram_backend:v1.0
    container_name: foodgram_backend
    restart: always
    volumes:
      - foodgram_static_volume:/app/static/
      - foodgram_media_volume:/app/media/
      - foodgram_data_volume:/app/data/
    depends_on:
      - db_foodgram
    env_file:
      - .env

  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - foodgram_static_volume:/var/html/static
      - foodgram_media_volume:/var/html/media
    depends_on:
      - foodgram_backend

volumes:
  foodgram_static_volume:
  foodgram_media_volume:
  foodgram_data_volume:
