version: '3.8'

services:
  db:
    image: postgres:13.0-alpine
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - foodgram_postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env

  backend:
    image: dudeinn/foodgram_backend:v1.0
    volumes:
      - foodgram_static_volume:/app/static/
      - foodgram_media_volume:/app/media/
      - ../data/:/app/data/
    depends_on:
      - db
    env_file:
      - .env

  frontend:
    image: dudeinn/foodgram_frontend:v1.0
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - backend

  nginx:
    image: nginx:1.21.3-alpine
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - foodgram_static_volume:/var/html/static/
      - foodgram_media_volume:/var/html/media/
    depends_on:
      - frontend

volumes:
  foodgram_postgres_data:
  foodgram_static_volume:
  foodgram_media_volume:
