version: '3.8'

services:

  frontend:
    image: dudeinn/foodgram_frontend:v1.0
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - backend

  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env

  backend:
    image: dudeinn/foodgram_backend:v1.0
    container_name: foodgram_backend
    restart: always
    volumes:
      - static_volume:/app/static/
      - media_volume:/app/media/
      - redoc:/app/api/docs/
    depends_on:
      - db
    env_file:
      - .env

  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - redoc:/usr/share/nginx/html/api/docs/
      - static_volume:/var/html/static/
      - media_volume:/var/html/media/
    depends_on:
      - backend

volumes:
  postgres_data:
  static_volume:
  media_volume:
  redoc:
